# Generated by Django 4.2.4 on 2023-09-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=100)),
                ('mName', models.CharField(blank=True, max_length=100)),
                ('lName', models.CharField(max_length=100)),
                ('sName', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('firebase_local_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
